# Generated by Django 5.0.6 on 2024-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(related_name='skills', to='portfolio.project'),
        ),
    ]
