# Generated by Django 5.0.6 on 2024-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skill_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='skills', to='portfolio.project'),
        ),
    ]
